/** Whoa rares (>=500 TC) with real runners. */
import type { WishTool } from "./wishCatalog";

export const WHOA_RARES: WishTool[] = [
  {
    id: "stegoverify",
    n: "Stego Roundtrip",
    cost: 650,
    tier: "rare",
    blurb: "Hide → extract → verify match. Companion desk for Stego Drop.",
    how: ["Upload a cover PNG", "Enter a short secret", "Tap Hide → Reveal → Verify"],
    body: "One-desk LSB roundtrip. Downloads stego PNG and reports MATCH/MISMATCH. Demo-grade — not covert.",
    hint: "Prove a stego hide/extract roundtrip matched before you trust the PNG.",
    tags: ["stego", "png", "roundtrip", "verify", "whoa", "lsb"],
  },
  {
    id: "waveform",
    n: "Waveform Stamp",
    cost: 700,
    tier: "rare",
    blurb: "Audio → waveform PNG with an optional stamp line. Shareable.",
    how: ["Upload audio", "Set stamp text", "Download PNG / share card"],
    body: "Web Audio peak waveform on canvas. Offline whoa for demos and invites.",
    hint: "Paint a waveform from real audio and stamp a line on the PNG.",
    tags: ["audio", "waveform", "stamp", "whoa", "share"],
  },
  {
    id: "glitch",
    n: "Channel Glitch",
    cost: 550,
    tier: "rare",
    blurb: "RGB channel-shift any photo into a glitch PNG.",
    how: ["Upload an image", "Slide the channel offset", "Download / share"],
    body: "Client pixel desk. Red/blue offset whoa — no filters as a service.",
    hint: "Glitch a photo with an RGB channel shift and share the PNG.",
    tags: ["image", "glitch", "rgb", "whoa", "share"],
  },
  {
    id: "jsongate",
    n: "JSON Schema Gate",
    cost: 600,
    tier: "rare",
    blurb: "Validate JSON against a small schema — path errors listed.",
    how: ["Paste JSON and schema", "Tap Validate", "Read OK or path errors"],
    body: "Subset: type, required, properties, min/max, minLength/maxLength, enum. Offline.",
    hint: "Gate a payload against a tiny JSON Schema before you ship it.",
    tags: ["json", "schema", "validate", "api", "gate"],
  },
  {
    id: "jsonpatch",
    n: "JSON Patch Desk",
    cost: 550,
    tier: "rare",
    blurb: "A → B deep diff mounted as RFC6902-style ops.",
    how: ["Paste JSON A and B", "Tap Build patch", "Copy the ops"],
    body: "Heuristic patch from deep path diff. Review before applying elsewhere.",
    hint: "Turn two JSON blobs into a copyable JSON Patch.",
    tags: ["json", "patch", "diff", "rfc6902", "api"],
  },
  {
    id: "palift",
    n: "Palette Lift",
    cost: 500,
    tier: "rare",
    blurb: "Lift 6 dominant hex colors from any image — tap to copy.",
    how: ["Upload an image", "Read the swatches", "Copy hex / share card"],
    body: "On-device quantize. Design whoa without a cloud palette API.",
    hint: "Pull a dominant hex palette out of a photo on this device.",
    tags: ["color", "palette", "image", "hex", "whoa", "design"],
  }
];
